### ISSUE TITLE
Creating a Hard-cap setting for thread-usage%

### ISSUE THREAD

**Issue by ByPaco10** [KingContaria/seedqueue#21]
Some lower-end systems (and some high-end) have massive lag spikes and audio problems when reseting a wall, creating a hard-cap for thread usage in % should give the system some room to not lag and prevent audio issues

**Comment by KingContaria** [comment]
A quick google search has given me the following info:

https://wrapper.tanukisoftware.com/doc/english/qna-processor-affinity.html
To implement SeedQueue setting Minecrafts process affinity I would have to either write platform specific code and interact with the OS in ways im not necessarily comfortable with or include a library that has this functionality.

https://answers.microsoft.com/en-us/windows/forum/all/how-to-permanently-set-priority-affinity-with/4e83fd39-34a7-49fe-a54a-ee891c38b737
On the other hand this article (if I'm understanding it correctly) seems to explain how to set affinity for a program as a user, but I'm not sure it works with how Minecraft is launched because I didn't actually fully read the article or test it out myself. If anyone does, please report your findings here :)

**Comment by ByPaco10** [comment]
> A quick google search has given me the following info:
> 
> https://wrapper.tanukisoftware.com/doc/english/qna-processor-affinity.html To implement SeedQueue setting Minecrafts process affinity I would have to either write platform specific code and interact with the OS in ways im not necessarily comfortable with or include a library that has this functionality.
> 
> https://answers.microsoft.com/en-us/windows/forum/all/how-to-permanently-set-priority-affinity-with/4e83fd39-34a7-49fe-a54a-ee891c38b737 On the other hand this article (if I'm understanding it correctly) seems to explain how to set affinity for a program as a user, but I'm not sure it works with how Minecraft is launched because I didn't actually fully read the article or test it out myself. If anyone does, please report your findings here :)

Doing some heavy testing on both a Ryzen 5 1600 system and i5 12600K system the affinity setting on Linux (Using taskset) and Windows (Using the article you provided) worked, but this is very system specific so I can't give a definitive answer of how good it works for all cases.

**Comment by KingContaria** [comment]
> Doing some heavy testing on both a Ryzen 5 1600 system and i5 12600K system the affinity setting on Linux (Using taskset) and Windows (Using the article you provided) worked, but this is very system specific so I can't give a definitive answer of how good it works for all cases.

It's true that it's very system specific but so would be an implementation in SeedQueue, which in my opinion is more brittle since it has to be tested to work for any environment, instead of users being able to use what works for their system.
I'm going to close this as not planend
